version: "3"

services:

    shopware:
        image: dockware/${IMAGE_TAG:-dev}:${SHOPWARE_VERSION:-latest}
        container_name: ${CONTAINER_NAME:-SW6_NEW_CONTAINER}
        ports:
            - "22:22"     # ssh
            - "80:80"     # apache2
            - "443:443"   # apache2 https
            - "8888:8888" # watch admin
            - "9998:9998" # watch storefront proxy
            - "9999:9999" # watch storefront
            - "3306:3306" # mysql port
        networks:
            - web
        volumes:
            - "./src/plugins:/var/www/html/custom/plugins"
        environment:
            - PHP_VERSION=${PHP_VERSION:-7.4}  # switch php version
            - NODE_VERSION=${NODE_VERSION:-16} # switch node version [12|14|16]
            - XDEBUG_ENABLED=${XDEBUG:-0}      # disabled because of performance for compiling
            # - COMPOSER_VERSION=2               # switch composer version [1|2]
            # - TZ=Europe/Berlin                 # custom timezone
            # - SW_CURRENCY=GBP                  # currency [standard EURO]

networks:
    web:
        external: false
